services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=utr'
      - 'POSTGRES_PASSWORD=tilapias'
      - 'POSTGRES_USER=utr'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata: